name: generate panvimdocs

on:
  push:
    branches:
      - main
    paths:
      - README.md

jobs:
  docs:
    runs-on: ubuntu-latest
    name: generate vimdoc
    steps:
      - uses: actions/checkout@v4
      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: harpoonline
          version: "Neovim >= 0.9.0"
          demojify: true
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(docs): auto-generate vimdoc"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
